# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_auto_20160802_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
