# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_auto_20160821_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='guide',
            name='teaser',
            field=models.CharField(max_length=100),
        ),
    ]
