# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='is_open',
        ),
    ]
