# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0002_remove_tournament_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='latest_loss',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
