# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='tournament',
        ),
    ]
