# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 05:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0005_auto_20160823_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('score_winner', models.IntegerField()),
                ('score_loser', models.IntegerField()),
                ('loser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_losers', to='ladder.Participant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladder.Tournament')),
                ('winner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_winners', to='ladder.Participant')),
            ],
        ),
    ]
