# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0006_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='loser',
        ),
        migrations.AddField(
            model_name='match',
            name='loser',
            field=models.ManyToManyField(related_name='match_loser', to='ladder.Participant'),
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ManyToManyField(related_name='match_winner', to='ladder.Participant'),
        ),
    ]
