# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0007_auto_20160826_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='loser',
            field=models.ManyToManyField(null=True, related_name='match_loser', to='ladder.Participant'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ManyToManyField(null=True, related_name='match_winner', to='ladder.Participant'),
        ),
    ]
