# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-28 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0008_auto_20160826_0334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['ranking']},
        ),
    ]
