# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-28 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0009_auto_20160828_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='loser',
        ),
        migrations.AddField(
            model_name='match',
            name='loser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_loser', to='ladder.Participant'),
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_winner', to='ladder.Participant'),
        ),
    ]
