# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-28 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0010_auto_20160828_0155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-date']},
        ),
    ]
