# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0011_auto_20160828_0159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterField(
            model_name='participant',
            name='ranking',
            field=models.IntegerField(),
        ),
    ]
