# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-01 22:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0007_auto_20161001_1840'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0002_player_clan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingamename', models.CharField(max_length=25)),
                ('avatar', models.ImageField(blank=True, upload_to=b'profile_images')),
                ('steamid', models.IntegerField(blank=True, null=True)),
                ('clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clans.Clan')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='clan',
        ),
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
