# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('clantag', models.CharField(max_length=4)),
                ('image', models.ImageField(upload_to=b'')),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
