# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-24 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='slug',
            field=models.SlugField(),
        ),
    ]
