# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 01:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0005_auto_20160824_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 31, 22, 21, 47, 934000)),
        ),
    ]
